# Change these first
owner: rocket-meals # Your GitHub organization or username, where this repository lives
repo: rocket-meals-uptime # The name of this repository

sites:
  - name: Test Rocket Meals - API Settings
    url: https://test.rocket-meals.de/rocket-meals/api/items/app_settings
    icon: https://test.rocket-meals.de/rocket-meals/api/assets/d9c13781-1b83-411a-83d4-562e50b85a0b
  - name: Test Rocket Meals - API Canteens
    url: https://test.rocket-meals.de/rocket-meals/api/items/canteens
    icon: https://test.rocket-meals.de/rocket-meals/api/assets/d9c13781-1b83-411a-83d4-562e50b85a0b
  - name: Test Rocket Meals - API Ping
    url: https://test.rocket-meals.de/rocket-meals/api/server/ping
    icon: https://test.rocket-meals.de/rocket-meals/api/assets/d9c13781-1b83-411a-83d4-562e50b85a0b
  - name: Test Rocket Meals - Web
    url: https://rocket-meals.github.io/rocket-meals/
    icon: https://test.rocket-meals.de/rocket-meals/api/assets/d9c13781-1b83-411a-83d4-562e50b85a0b
  - name: SWOSY - API Settings
    url: https://swosy.rocket-meals.de/rocket-meals/api/items/app_settings
    icon: https://swosy.rocket-meals.de/rocket-meals/api/assets/443ed197-ac6b-49c6-a004-525c0d00683d
  - name: SWOSY - API Canteens
    url: https://swosy.rocket-meals.de/rocket-meals/api/items/canteens
    icon: https://swosy.rocket-meals.de/rocket-meals/api/assets/443ed197-ac6b-49c6-a004-525c0d00683d
  - name: SWOSY - API Ping
    url: https://swosy.rocket-meals.de/rocket-meals/api/server/ping
    icon: https://swosy.rocket-meals.de/rocket-meals/api/assets/443ed197-ac6b-49c6-a004-525c0d00683d
  - name: SWOSY - Web
    url: https://rocket-meals.github.io/swosy/
    icon: https://swosy.rocket-meals.de/rocket-meals/api/assets/443ed197-ac6b-49c6-a004-525c0d00683d
  - name: Studi-Futter - API Appsettings
    url: https://studi-futter.rocket-meals.de/rocket-meals/api/items/app_settings
    icon: https://studi-futter.rocket-meals.de/rocket-meals/api/assets/3410fefc-9447-49ce-ae8e-0cd9f2129d8a
  - name: Studi-Futter - API Canteens
    url: https://studi-futter.rocket-meals.de/rocket-meals/api/items/canteens
    icon: https://studi-futter.rocket-meals.de/rocket-meals/api/assets/3410fefc-9447-49ce-ae8e-0cd9f2129d8a
  - name: Studi-Futter - API Ping
    url: https://studi-futter.rocket-meals.de/rocket-meals/api/server/ping
    icon: https://studi-futter.rocket-meals.de/rocket-meals/api/assets/3410fefc-9447-49ce-ae8e-0cd9f2129d8a
  - name: Studi-Futter - Web
    url: https://rocket-meals.github.io/studi-futter/
    icon: https://studi-futter.rocket-meals.de/rocket-meals/api/assets/3410fefc-9447-49ce-ae8e-0cd9f2129d8a


workflowSchedule:
  graphs: "*/10 * * * *"
  responseTime: "*/10 * * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/10 * * * *"

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /rocket-meals-uptime
  logoUrl: https://avatars.githubusercontent.com/u/139654808?s=200&v=4
  name: Rocket-Meals Uptime Status
  theme: light # Available themes are light, dark, night or ocean.
  introTitle: "Uptime monitor and status page"
  introMessage: This pages monitors the status of several Rocket-Meals server instances and API Routes.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
